

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.*;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import javax.swing.*;
import javax.swing.border.Border;
public class Receipt extends javax.swing.JFrame {

    /**
     * Creates new form Receipt
     */
    public Receipt() {
        initComponents();
    }
    
        public Receipt(String receiptHeader, String receiptData, String receiptFooter) {
        initComponents();
        
        Header.setText(receiptHeader);
        
        Order.setText(receiptData);
        
        Footer.setText(receiptFooter);
        
        scrollHeader.setBorder(null);
        Header.setBorder(null);
        
        scrollOrder.setBorder(null);
        Order.setBorder(null);
        
        scrollFooter.setBorder(null);
        Footer.setBorder(null);
        printReceipt.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pane = new javax.swing.JPanel();
        scrollHeader = new javax.swing.JScrollPane();
        Header = new javax.swing.JTextArea();
        scrollOrder = new javax.swing.JScrollPane();
        Order = new javax.swing.JTextArea();
        scrollFooter = new javax.swing.JScrollPane();
        Footer = new javax.swing.JTextArea();
        printReceipt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        pane.setBackground(new java.awt.Color(255, 255, 255));
        pane.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        pane.setForeground(new java.awt.Color(255, 255, 255));

        Header.setEditable(false);
        Header.setBackground(new java.awt.Color(255, 255, 255));
        Header.setColumns(20);
        Header.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        Header.setRows(5);
        Header.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        Header.setCaretColor(new java.awt.Color(255, 255, 255));
        scrollHeader.setViewportView(Header);

        Order.setEditable(false);
        Order.setBackground(new java.awt.Color(255, 255, 255));
        Order.setColumns(20);
        Order.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        Order.setRows(5);
        Order.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        Order.setCaretColor(new java.awt.Color(255, 255, 255));
        scrollOrder.setViewportView(Order);

        Footer.setEditable(false);
        Footer.setBackground(new java.awt.Color(255, 255, 255));
        Footer.setColumns(20);
        Footer.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        Footer.setRows(5);
        Footer.setCaretColor(new java.awt.Color(255, 255, 255));
        scrollFooter.setViewportView(Footer);

        printReceipt.setText("Print Receipt");
        printReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printReceiptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneLayout = new javax.swing.GroupLayout(pane);
        pane.setLayout(paneLayout);
        paneLayout.setHorizontalGroup(
            paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollHeader)
            .addComponent(scrollFooter, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
            .addComponent(scrollOrder)
            .addGroup(paneLayout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(printReceipt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneLayout.setVerticalGroup(
            paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneLayout.createSequentialGroup()
                .addComponent(scrollHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollFooter, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(printReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void printReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printReceiptActionPerformed
 printReceipt.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                PrinterJob job = PrinterJob.getPrinterJob();
                job.setJobName("Print Frame");

                job.setPrintable(new Printable() {
                    @Override
                    public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
                        if (pageIndex > 0) {
                            return Printable.NO_SUCH_PAGE;
                        }

                        Graphics2D g2d = (Graphics2D)graphics;
                        g2d.translate(pageFormat.getImageableX(), pageFormat.getImageableY());

                        pane.printAll(graphics);

                        return Printable.PAGE_EXISTS;
                    }
                });

                boolean doPrint = job.printDialog();
                if (doPrint) {
                    try {
                        job.print();
                        
                    } catch (PrinterException ex) {
                        ex.printStackTrace();
                    }
                }
            }
        });
    }//GEN-LAST:event_printReceiptActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Receipt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Footer;
    private javax.swing.JTextArea Header;
    private javax.swing.JTextArea Order;
    private javax.swing.JPanel pane;
    private javax.swing.JButton printReceipt;
    private javax.swing.JScrollPane scrollFooter;
    private javax.swing.JScrollPane scrollHeader;
    private javax.swing.JScrollPane scrollOrder;
    // End of variables declaration//GEN-END:variables
}
